<?php
session_start();
if(!isset($_SESSION['user_type']) || $_SESSION['user_type'] != 'admin') {
    header("Location: ../auth/login.php");
    exit();
}

require_once '../config/database.php';
require_once '../includes/functions.php';

$database = new Database();
$db = $database->getConnection();

if (isset($_POST['generate_bulk'])) {
    $items = $_POST['items'] ?? [];
    $type = $_POST['type'] ?? 'CODE128';
    
    $generated = [];
    foreach ($items as $item) {
        if (!empty(trim($item))) {
            $barcodeFile = generateBarcode(trim($item), $type);
            $generated[] = [
                'data' => trim($item),
                'file' => $barcodeFile
            ];
        }
    }
    
    $_SESSION['generated_barcodes'] = $generated;
    header("Location: barcode_bulk.php?success=1");
    exit;
}

include '../includes/header.php';
?>

<div class="container mt-4">
    <h2>Bulk Barcode Generator</h2>
    
    <?php if(isset($_GET['success'])): ?>
    <div class="alert alert-success">Barcodes generated successfully!</div>
    <?php endif; ?>
    
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h5 class="mb-0">Generate Multiple Barcodes</h5>
                </div>
                <div class="card-body">
                    <form method="POST">
                        <div class="mb-3">
                            <label class="form-label">Barcode Type</label>
                            <select name="type" class="form-control">
                                <option value="CODE128">CODE128</option>
                                <option value="CODE39">CODE39</option>
                                <option value="QRCODE">QR Code</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Enter items (one per line)</label>
                            <textarea name="items[]" class="form-control" rows="10" 
                                      placeholder="Item 1&#10;Item 2&#10;Item 3"></textarea>
                            <small class="text-muted">Enter each barcode content on a new line</small>
                        </div>
                        <button type="submit" name="generate_bulk" class="btn btn-primary">
                            Generate Barcodes
                        </button>
                    </form>
                </div>
            </div>
        </div>
        
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h5 class="mb-0">Generated Barcodes</h5>
                </div>
                <div class="card-body">
                    <?php if(isset($_SESSION['generated_barcodes'])): ?>
                        <?php foreach($_SESSION['generated_barcodes'] as $barcode): ?>
                        <div class="barcode-item mb-3 p-2 border rounded">
                            <div class="text-center">
                                <img src="<?php echo $barcode['file']; ?>" alt="Barcode" class="img-fluid" style="max-height: 80px;">
                            </div>
                            <div class="text-center mt-1">
                                <small><?php echo htmlspecialchars($barcode['data']); ?></small>
                                <br>
                                <button class="btn btn-sm btn-outline-primary mt-1" onclick="printSingleBarcode('<?php echo $barcode['file']; ?>', '<?php echo htmlspecialchars($barcode['data']); ?>')">
                                    <i class="fas fa-print"></i> Print
                                </button>
                            </div>
                        </div>
                        <?php endforeach; ?>
                        <button class="btn btn-success w-100" onclick="printAllBarcodes()">
                            <i class="fas fa-print"></i> Print All Barcodes
                        </button>
                    <?php else: ?>
                        <p class="text-muted">No barcodes generated yet.</p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Print Template -->
<div id="printTemplate" style="display: none;">
    <div id="barcodePrintContent"></div>
</div>

<script>
function printSingleBarcode(barcodeUrl, data) {
    const printContent = `
        <div style="text-align: center; padding: 20px; font-family: Arial, sans-serif;">
            <img src="${barcodeUrl}" alt="Barcode" style="max-width: 100%; height: auto;">
            <div style="margin-top: 10px; font-size: 14px;">${data}</div>
            <div style="margin-top: 5px; font-size: 10px; color: #666;">Generated by MDVA System</div>
        </div>
    `;
    
    printBarcodeContent(printContent);
}

function printAllBarcodes() {
    const barcodeItems = document.querySelectorAll('.barcode-item');
    let printContent = '<div style="display: flex; flex-wrap: wrap; gap: 10px; padding: 20px;">';
    
    barcodeItems.forEach(item => {
        const img = item.querySelector('img');
        const text = item.querySelector('small').textContent;
        printContent += `
            <div style="flex: 0 0 calc(33.333% - 10px); text-align: center; padding: 10px; border: 1px solid #ccc;">
                <img src="${img.src}" alt="Barcode" style="max-width: 100%; height: 60px;">
                <div style="margin-top: 5px; font-size: 12px;">${text}</div>
            </div>
        `;
    });
    
    printContent += '</div>';
    printBarcodeContent(printContent);
}

function printBarcodeContent(content) {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
            <title>Print Barcodes</title>
            <style>
                body { margin: 0; padding: 10px; font-family: Arial, sans-serif; }
                @media print {
                    body { margin: 0; padding: 0; }
                }
            </style>
        </head>
        <body>
            ${content}
            <script>
                window.onload = function() {
                    window.print();
                    setTimeout(function() {
                        window.close();
                    }, 500);
                };
            <\/script>
        </body>
        </html>
    `);
    printWindow.document.close();
}
</script>

<?php include '../includes/footer.php'; ?>